### ISSUE TITLE
make the proper ordered listing of the months

### ISSUE THREAD

**Issue by niyoj** [Ayan-thecodeking/Opportunities-HUB#16]
## What is this issue?
This issue is just that for the files for corresponding months like `1.jan.md`, proper order is not maintained like `5.aug.md` comes after `4.april.md` while we expect `5.may.md` to be there but it is named as `8.may.md` in the repo.

## Why is this needed?

- To maintain the visual hierarchy level,
- When the repo is downloaded the arrangement of the files seems random so, arranging the files by naming on the basis of their month in numbers as prefix will fix that issue.

**Comment by niyoj** [comment]
You can assign this task to me as I want to start my open source journey.

**Comment by Ayan-thecodeking** [comment]
go ahead @niyoj every contribution matters :)

**Comment by niyoj** [comment]
Here is the PR for the updated file hierarchy.
